services:
  gopay-gateway:
    build: .
    container_name: gopay-gateway
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    networks:
      - app_shared_net

networks:
  app_shared_net:
    external: true
