version: '3.8'

services:
  gopay-gateway:
    build: .
    container_name: gopay-gateway
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    volumes:
      - ./gateway.db:/app/gateway.db
      - ./.GOPAY_SESI_JANGAN_DIHAPUS.json:/app/.GOPAY_SESI_JANGAN_DIHAPUS.json
